hands-on-004

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,7 +1,7 @@
-name: My workflow
+name: Feature
 on:
-  push: 
-    branches: main
+  push:
+      - main
 
 jobs:
   build-image:
@@ -15,3 +15,33 @@ jobs:
 
       - name: Build Image
         run: docker build -t ${{ github.event.repository.name }}:latest .
+
+  unit-tests:
+    name: Unit Tests
+    runs-on: ubuntu-latest
+    outputs:
+      result: ${{ steps.unit-tests.outputs.unit-test-result }}
+    steps:
+      - name: Checkout Source
+        uses: actions/checkout@v2
+
+      - name: Run Unit Tests
+        env:
+          NAME: sean
+        run: |
+          echo "Unit Tests are running..."
+          if [ "$NAME" = "sean" ]; then 
+            echo "::set-output name=unit-test-result::PASS"
+            echo "pass" && exit 0
+          else
+            echo "::set-output name=unit-test-result::FAIL"
+            echo "fail" && exit 1
+          fi
+
+  collate-test-results:
+    name: Unit Tests
+    runs-on: ubuntu-latest
+    needs: unit-tests
+    steps:
+      - name: Print Results
+        run: echo "The result of the Unit Tests was ${{ needs.unit-tests.outputs.result }}"
